---
title: "Career"
description: I'm a researcher and data journalist with a focus on visualising and communicating climate change.
listing:
  - contents: talks
    id: about-talks
    type: grid
    sort: "date desc"
    page-size: 3
    sort-ui: false
    filter-ui: false
  - contents: portfolio
    id: about-portfolio
    type: grid
    sort: "date desc"
    page-size: 3
    sort-ui: false
    filter-ui: false
---

Right now I'm working at [360info](https://newshub.360info.org) as the Data and Digital Storytelling Lead, building the data visualisation and analysis capability of an open newswire supported by Monash University.

Here are some of the more ambitious interactives I've produced:

::::{.column-screen-inset}
### **Featured work**
:::{#about-portfolio}
:::
::::

:::{.column-margin}

```{=html}
<div style="text-align:center; position: relative; height: 0; padding-bottom: 178%; margin-top: 25px; margin-bottom: 25px; border: 1px solid #cccccc; border-radius: 5px;">
	<iframe style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; background-color: white" src="https://youtube.com/embed/yDAae7EWqD8?si=EjRF6V9WIFivV8bX" allowfullscreen></iframe>
</div>
<figcaption class="figure-caption">360info video on marine heatwaves</figcaption>
```
:::

I also occasionally commission and edit stories alongside our other editors. Here're some of the stories I've written or commissioned:

- [How dangerous is extreme heat to humans](https://360info.org/how-dangerous-is-extreme-heat-to-humans/) (Commissioned August 2023)
- [Renters in older homes feeling the heat ](https://360info.org/renters-in-older-homes-feeling-the-heat/) (Written March 2023)
- [Extreme heat will put more pressure on workers](https://360info.org/extreme-heat-will-put-more-pressure-on-workers/) (Written February 2023)
- [The ecological crisis in the Arctic Ocean](https://360info.org/the-ecological-crisis-in-the-arctic-ocean/) (Comissioned October 2022)
- [Seeing emotions just the start for brain-reading technology](https://360info.org/seeing-emotions-just-the-start-for-brain-reading-technology/) (Comissioned September 2022)

Beyond our big interactives, I produce static charts and infographics, train our interns in data storytelling, work with our media partners to help them use our interactives and datasets, and manage our [GitHub presence](https://github.ciom/360-info), working to make our data and graphics more discoverable.

I also appear in the odd video!

Although I work in data journalism, I have a background researching the public health impacts of climate change. [Here's my published research.](https://scholar.google.com/citations?user=Otq-xj0AAAAJ&hl=en)

I sometimes give talks on data visualisation, storytelling, open data science and climate change:

::::{.column-screen-inset}
### **Talks**
:::{#about-talks}
:::
::::

Have ideas about communicating climate change or other big ideas better? [I'm always happy to talk!](mailto:me@jamesgoldie.dev)
